In [4]:
import pandas as pd 
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv("HR_data.csv")
df.head()

,satisfaction_level,last_evaluation,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,Department,salary
0,0.38,0.53,2,157,3,0,1,0,sales,low
1,0.80,0.86,5,262,6,0,1,0,sales,medium
2,0.11,0.88,7,272,4,0,1,0,sales,medium
3,0.72,0.87,5,223,5,0,1,0,sales,low
4,0.37,0.52,2,159,3,0,1,0,sales,low

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14999 entries, 0 to 14998
Data columns (total 10 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   satisfaction_level     14999 non-null  float64
 1   last_evaluation        14999 non-null  float64
 2   number_project         14999 non-null  int64
 3   average_montly_hours   14999 non-null  int64
 4   time_spend_company     14999 non-null  int64
 5   Work_accident          14999 non-null  int64
 6   left                   14999 non-null  int64
 7   promotion_last_5years  14999 non-null  int64
 8   Department             14999 non-null  object
 9   salary                 14999 non-null  object
dtypes: float64(2), int64(6), object(2)
memory usage: 1.1+ MB

In [ ]:
dummies = pd.get_dummies(df[['Department', 'salary']])
merged = pd.concat([df, dummies], axis="columns")
merged

,satisfaction_level,last_evaluation,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,Department,salary,...,Department_hr,Department_management,Department_marketing,Department_product_mng,Department_sales,Department_support,Department_technical,salary_high,salary_low,salary_medium
0,0.38,0.53,2,157,3,0,1,0,sales,low,...,False,False,False,False,True,False,False,False,True,False
1,0.80,0.86,5,262,6,0,1,0,sales,medium,...,False,False,False,False,True,False,False,False,False,True
2,0.11,0.88,7,272,4,0,1,0,sales,medium,...,False,False,False,False,True,False,False,False,False,True
3,0.72,0.87,5,223,5,0,1,0,sales,low,...,False,False,False,False,True,False,False,False,True,False
4,0.37,0.52,2,159,3,0,1,0,sales,low,...,False,False,False,False,True,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14994,0.40,0.57,2,151,3,0,1,0,support,low,...,False,False,False,False,False,True,False,False,True,False
14995,0.37,0.48,2,160,3,0,1,0,support,low,...,False,False,False,False,False,True,False,False,True,False
14996,0.37,0.53,2,143,3,0,1,0,support,low,...,False,False,False,False,False,True,False,False,True,False
14997,0.11,0.96,6,280,4,0,1,0,support,low,...,False,False,False,False,False,True,False,False,True,False
14998,0.37,0.52,2,158,3,0,1,0,support,low,...,False,False,False,False,False,True,False,False,True,False

In [21]:
model = LogisticRegression()
X_train, X_test, y_train, y_test = train_test_split(merged.drop(['Department','salary','left'],axis="columns"),merged['left'],train_size=0.8)
X_test

,satisfaction_level,last_evaluation,number_project,average_montly_hours,time_spend_company,Work_accident,promotion_last_5years,Department_IT,Department_RandD,Department_accounting,Department_hr,Department_management,Department_marketing,Department_product_mng,Department_sales,Department_support,Department_technical,salary_high,salary_low,salary_medium
14493,0.83,0.92,5,267,6,0,0,False,False,False,False,False,False,False,False,True,False,False,True,False
6403,0.68,0.70,5,270,3,0,0,False,False,False,False,False,False,True,False,False,False,False,False,True
12725,0.43,0.46,2,149,3,0,0,False,False,False,False,False,False,False,False,False,True,False,False,True
11522,0.50,0.92,4,266,7,0,0,False,False,False,False,False,False,True,False,False,False,False,False,True
6503,0.59,0.57,4,197,2,0,0,False,False,False,False,False,False,False,True,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11839,0.49,0.62,4,161,2,0,0,True,False,False,False,False,False,False,False,False,False,False,False,True
7491,0.91,0.60,4,133,4,1,0,False,False,False,False,False,False,False,True,False,False,False,False,True
151,0.45,0.56,2,154,3,0,0,False,False,False,False,False,True,False,False,False,False,False,True,False
9191,0.32,0.95,2,184,5,0,0,False,False,False,True,False,False,False,False,False,False,False,False,True
7134,0.86,0.88,4,274,3,0,0,False,False,False,True,False,False,False,False,False,False,False,False,True

In [22]:
model.fit(X_test,y_test)

/Users/srijachillara/Library/Python/3.10/lib/python/site-packages/sklearn/linear_model/_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [23]:
model.predict(X_test)

array([0, 0, 0, ..., 0, 1, 0], shape=(3000,))

In [24]:
model.score(X_test,y_test)

0.8003333333333333